# Generated by Django 3.0.3 on 2020-02-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('completed', models.BooleanField(blank=True, default=False)),
                ('url', models.CharField(max_length=250)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
