app:
  build: ../../
  dockerfile: docker/release/Dockerfile
  links:
    - db
  volumes_from:
    - webroot
  environment:
    DJANGO_SETTINGS_MODULE: todobackend.settings.release
    MYSQL_HOST: db
    MYSQL_DATABASE: todobackend
    MYSQL_USER: todo
    MYSQL_PASSWORD: password
    DEBUG: "true"
  command:
    - uwsgi
    - "--socket /var/www/todobackend/todobackend.sock"
    - "--chmod-socket=666"
    - "--module todobackend.wsgi"
    - "--master"
    - "--die-on-term"

db:
  image: mysql:5.6
  expose:
    - "3306"
  environment:
    MYSQL_DATABASE: todobackend
    MYSQL_USER: todo
    MYSQL_PASSWORD: password
    MYSQL_ROOT_PASSWORD: password


nginx:
  build: .
  dockerfile: Dockerfile.nginx
  links:
    - app
  ports:
    - 8000:8000
  volumes_from:
    - webroot
agent:
  image: aman0511/ansible
  links:
    - db
  environment:
      PROBE_HOST: 'db'
      PROBE_PORT: 3306
  command: ["probe.yml"]


webroot:
  build: ../../
  dockerfile: docker/release/Dockerfile
  volumes:
    - /var/www/todobackend
  entrypoint: "true"
